---
- name: Install mongodb
  hosts: all
  become: yes
  tasks:
  - name: add apt key
    apt_key:
      id: EA312927
      keyserver: keyserver.ubuntu.com
  
  - name: add apt repo
    apt_repository:
      repo: deb [ arch=amd64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
      state: present
  
  - name: install mongodb
    apt:
      name: mongodb-org
      state: present
      update_cache: yes

  - name: enable mongodb service
    systemd:
      name: mongod
      enabled: yes
